name: CI/CD Pipeline with SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies and run tests
        run: |
          pip install --upgrade pip
          pip install coverage
          coverage run -m unittest discover
          coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarCloud Quality Gate
        uses: SonarSource/sonarcloud-quality-gate-action@master
        with:
          timeout: '300' # Waits up to 5 minutes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy only if Quality Gate passed
        if: success()  # This will run only if all above steps succeeded
        run: echo "🚀 Deployed successfully because tests and analysis passed!"
