name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube + Test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          coverage run -m unittest discover
          coverage xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy if all passed
    runs-on: ubuntu-latest
    needs: sonarqube
    if: success() # This ensures deploy runs only if previous job succeeds

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mock Deployment
        run: echo "🚀 Deployed successfully because tests and analysis passed!"
